--
-- Go to right DB & Schema
--
USE SCHEMA BI.MANUAL_ENTRY;

-- 
-- Confirm task is idle and right time to make changes
--
SELECT CASE DATEDIFF(HOUR, COMPLETED_TIME, CURRENT_TIMESTAMP) WHEN 0 THEN 'OK' ELSE 'WAIT' END DOABLE
    ,DATEDIFF(MINUTE, CURRENT_TIMESTAMP, DATEADD(MINUTE, 75, DATE_TRUNC(HOUR,COMPLETED_TIME))) NEXT_SCHEDULE_IN_MINUTES
    ,DATEADD(MINUTE, 75, DATE_TRUNC(HOUR,COMPLETED_TIME)) NEXT_SCHEDULE_TIME 
    ,COMPLETED_TIME LAST_COMPLETION_TIME
    ,CURRENT_TIMESTAMP
FROM BI._CONTROL_LOGIC.DATA_AGGREGATION_COMPLETION_TIME
;

--
-- Setup a monthly forecast
--
INSERT INTO SELLSIDE_CONTRACT_MANUAL_ENTRY_CONFIGURATION (
    SELLSIDE_CONTRACT_ID,
    REVENUE_MONTH,
    MONTHLY_REVENUE_FORECAST,
    DATES_IN_MONTH
)
SELECT $1, $2, $3, PARSE_JSON($4)
FROM VALUES (
    16,             -- SELLSIDE_CONTRACT_ID
    '2020-01-01',   -- REVENUE_MONTH
    50000,          -- MONTHLY_REVENUE_FORECAST
    '[12,13]'       -- DATES_IN_MONTH, preset the past dates
);

--
-- Confirm the setup
--
SELECT REVENUE_MONTH
    ,MONTHLY_REVENUE_FORECAST
    ,MONTHLY_REVENUE_ACTUAL
FROM SELLSIDE_CONTRACT_MANUAL_ENTRY_CONFIGURATION
WHERE SELLSIDE_CONTRACT_ID = 16
ORDER BY REVENUE_MONTH DESC
;
